#!/usr/bin/env python
from __future__ import print_function

import sys
import xml.dom.minidom

(fileName, attrName) = sys.argv[1:]

xmldoc = xml.dom.minidom.parse( fileName )
print( xmldoc.childNodes[0].getAttribute( attrName ) )
