# -*- coding: utf-8 -*-

# Most of this file is not used directly in addon, but is used by gettext for translations.
# Do not remove it

def _(s):
	return s

genres_list = (
	_("Erotic"),
	_("Pornographic"),
	_("Action"),
	_("Adult"),
	_("Animated"),
	_("Animation"),
	_("Adventure"),
	_("Biographical"),
	_("Catastrophic"),
	_("Comedy"),
	_("Competition"),
	_("Crime"),
	_("Documentary"),
	_("Fairy Tale"),
	_("Drama"),
	_("Family"),
	_("Fantasy"),
	_("Historical"),
	_("Horror"),
	_("IMAX"),
	_("Educational"),
	_("Music"),
	_("Journalistic"),
	_("Military"),
	_("Musical"),
	_("Mysterious"),
	_("Psychological"),
	_("Reality"),
	_("Romance"),
	_("Sci-Fi"),
	_("Short"),
	_("Sports"),
	_("Stand-Up"),
	_("Talk-Show"),
	_("Telenovela"),
	_("Thriller"),
	_("Travel"),
	_("Western"),
	_("War")
)

country_list = (
	_("Algeria"),
	_("Argentina"),
	_("Armenia"),
	_("Aruba"),
	_("Australia"),
	_("Austria"),
	_("Azerbaijan"),
	_("Bahamas"),
	_("Bangladesh"),
	_("Belarus"),
	_("Belgium"),
	_("Bhutan"),
	_("Bolivia"),
	_("Bosnia and Herzegovina"),
	_("Botswana"),
	_("Brazil"),
	_("Brunei"),
	_("Bulgaria"),
	_("Cambodia"),
	_("Canada"),
	_("Chile"),
	_("China"),
	_("Colombia"),
	_("Costa Rica"),
	_("Croatia"),
	_("Cuba"),
	_("Cyprus"),
	_("Czechia"),
	_("Czechoslovakia"),
	_("Democratic Republic of the Congo"),
	_("Denmark"),
	_("Dominican republic"),
	_("East Germany"),
	_("Egypt"),
	_("Estonia"),
	_("Fed. Rep. Yugoslavia"),
	_("Finland"),
	_("France"),
	_("French Polynesia"),
	_("Georgia"),
	_("German Empire"),
	_("Germany"),
	_("Ghana"),
	_("Greece"),
	_("Haiti"),
	_("Hong Kong"),
	_("Hungary"),
	_("Iceland"),
	_("India"),
	_("Indonesia"),
	_("Iran"),
	_("Iraq"),
	_("Ireland"),
	_("Israel"),
	_("Italy"),
	_("Jamaica"),
	_("Japan"),
	_("Jordan"),
	_("Kazakhstan"),
	_("Kenya"),
	_("Laos"),
	_("Latvia"),
	_("Lebanon"),
	_("Lichtenstein"),
	_("Lithuania"),
	_("Luxembourg"),
	_("Macao"),
	_("Macedonia"),
	_("Malaysia"),
	_("Malta"),
	_("Mexico"),
	_("Monaco"),
	_("Mongolia"),
	_("Montenegro"),
	_("Morocco"),
	_("Namibia"),
	_("Nepal"),
	_("Netherlands"),
	_("New Zealand"),
	_("Nigeria"),
	_("North Korea"),
	_("Norway"),
	_("Pakistan"),
	_("Palestine"),
	_("Panama"),
	_("Papua New Guinea"),
	_("Paraguay"),
	_("Peru"),
	_("Philippines"),
	_("Poland"),
	_("Portugal"),
	_("Puerto Rico"),
	_("Qatar"),
	_("Romania"),
	_("Russia"),
	_("Saudi Arabia"),
	_("Senegal"),
	_("Serbia"),
	_("Serbia and Montenegro"),
	_("Singapore"),
	_("Slovakia"),
	_("Slovenia"),
	_("South African Republic"),
	_("South Korea"),
	_("Spain"),
	_("Sweden"),
	_("Switzerland"),
	_("Syria"),
	_("Taiwan"),
	_("Tanzania"),
	_("Thailand"),
	_("The Soviet Union"),
	_("Tunisia"),
	_("Turkey"),
	_("Uganda"),
	_("Ukraine"),
	_("United Arab Emirates"),
	_("United Kingdom"),
	_("United States of America"),
	_("Uruguay"),
	_("Venezuela"),
	_("Vietnam"),
	_("West Germany"),
	_("Yugoslavia"),
	_("Zimbabwe"),
)

lang_list = (
	_("Afar"),
	_("Abkhazian"),
	_("Afrikaans"),
	_("Amharic"),
	_("Arabic"),
	_("Assamese"),
	_("Aymara"),
	_("Azerbaijani"),
	_("Bashkir"),
	_("Byelorussian"),
	_("Bulgarian"),
	_("Bihari"),
	_("Bislama"),
	_("Bengali; Bangla"),
	_("Tibetan"),
	_("Breton"),
	_("Catalan"),
	_("Corsican"),
	_("Czech"),
	_("Welsh"),
	_("Danish"),
	_("German"),
	_("Bhutani"),
	_("Greek"),
	_("English"),
	_("Esperanto"),
	_("Spanish"),
	_("Estonian"),
	_("Basque"),
	_("Persian"),
	_("Finnish"),
	_("Fiji"),
	_("Faeroese"),
	_("French"),
	_("Frisian"),
	_("Irish"),
	_("Scots Gaelic"),
	_("Galician"),
	_("Guarani"),
	_("Gujarati"),
	_("Hausa"),
	_("Hebrew"),
	_("Hindi"),
	_("Croatian"),
	_("Hungarian"),
	_("Armenian"),
	_("Interlingua"),
	_("Indonesian"),
	_("Interlingue"),
	_("Inupiak"),
	_("Icelandic"),
	_("Italian"),
	_("Japanese"),
	_("Yiddish"),
	_("Javanese"),
	_("Georgian"),
	_("Kazakh"),
	_("Greenlandic"),
	_("Cambodian"),
	_("Kannada"),
	_("Korean"),
	_("Kashmiri"),
	_("Kurdish"),
	_("Kirghiz"),
	_("Latin"),
	_("Lingala"),
	_("Laothian"),
	_("Lithuanian"),
	_("Latvian, Lettish"),
	_("Malagasy"),
	_("Maori"),
	_("Macedonian"),
	_("Malayalam"),
	_("Mongolian"),
	_("Moldavian"),
	_("Marathi"),
	_("Malay"),
	_("Maltese"),
	_("Burmese"),
	_("Nauru"),
	_("Nepali"),
	_("Dutch"),
	_("Norwegian"),
	_("Occitan"),
	_("(Afan) Oromo"),
	_("Oriya"),
	_("Punjabi"),
	_("Polish"),
	_("Pashto, Pushto"),
	_("Portuguese"),
	_("Quechua"),
	_("Rhaeto-Romance"),
	_("Kirundi"),
	_("Romanian"),
	_("Russian"),
	_("Kinyarwanda"),
	_("Sanskrit"),
	_("Sindhi"),
	_("Sangro"),
	_("Serbo-Croatian"),
	_("Singhalese"),
	_("Slovak"),
	_("Slovenian"),
	_("Samoan"),
	_("Shona"),
	_("Somali"),
	_("Albanian"),
	_("Serbian"),
	_("Siswati"),
	_("Sesotho"),
	_("Sundanese"),
	_("Swedish"),
	_("Swahili"),
	_("Tamil"),
	_("Tegulu"),
	_("Tajik"),
	_("Thai"),
	_("Tigrinya"),
	_("Turkmen"),
	_("Tagalog"),
	_("Setswana"),
	_("Tonga"),
	_("Turkish"),
	_("Tsonga"),
	_("Tatar"),
	_("Twi"),
	_("Ukrainian"),
	_("Urdu"),
	_("Uzbek"),
	_("Vietnamese"),
	_("Volapuk"),
	_("Wolof"),
	_("Xhosa"),
	_("Yoruba"),
	_("Chinese"),
	_("Chinese"),
	_("Zulu"),
	_("Bosnian"),
	_("Inuktitut"),
	_("No Language"),
)

lang_code_to_lang = {
	"aa": "Afar",
	"ab": "Abkhazian",
	"af": "Afrikaans",
	"am": "Amharic",
	"ar": "Arabic",
	"as": "Assamese",
#	"ak":
	"ay": "Aymara",
	"az": "Azerbaijani",
	"ba": "Bashkir",
	"be": "Byelorussian",
	"bg": "Bulgarian",
	"bh": "Bihari",
	"bi": "Bislama",
	"bm": "Bermuda",
	"bn": "Bengali; Bangla",
	"bo": "Tibetan",
	"br": "Breton",
	"ca": "Catalan",
#	"ce":
	"co": "Corsican",
	"cr": "Costa Rica",
	"cs": "Czech",
	"cy": "Welsh",
	"da": "Danish",
	"de": "German",
	"dz": "Bhutani",
	"el": "Greek",
	"en": "English",
	"eo": "Esperanto",
	"es": "Spanish",
	"et": "Estonian",
	"eu": "Basque",
	"fa": "Persian",
	"fi": "Finnish",
	"fj": "Fiji",
	"fo": "Faeroese",
	"fr": "French",
	"fy": "Frisian",
	"ga": "Irish",
	"gd": "Scots Gaelic",
	"gl": "Galician",
	"gn": "Guarani",
	"gu": "Gujarati",
	"ha": "Hausa",
	"he": "Hebrew",
	"hi": "Hindi",
	"hr": "Croatian",
	"ht": "Haiti",
	"hu": "Hungarian",
	"hy": "Armenian",
	"ia": "Interlingua",
	"id": "Indonesian",
	"ie": "Interlingue",
#	"ig":
	"ik": "Inupiak",
	"is": "Icelandic",
	"it": "Italian",
	"ja": "Japanese",
	"ji": "Yiddish",
#	"jv":
	"jw": "Javanese",
	"ka": "Georgian",
	"kk": "Kazakh",
	"kl": "Greenlandic",
	"km": "Cambodian",
	"kn": "Kannada",
	"ko": "Korean",
	"ks": "Kashmiri",
	"ku": "Kurdish",
	"kw": "Kuwait",
	"ky": "Kirghiz",
	"la": "Latin",
	"lb": "Lebanon",
	"ln": "Lingala",
	"lo": "Laothian",
	"lt": "Lithuanian",
	"lv": "Latvian, Lettish",
	"mg": "Malagasy",
	"mi": "Maori",
	"mk": "Macedonian",
	"ml": "Malayalam",
	"mn": "Mongolian",
	"mo": "Moldavian",
	"mr": "Marathi",
	"ms": "Malay",
	"mt": "Maltese",
	"my": "Burmese",
	"na": "Nauru",
	"ne": "Nepali",
	"nl": "Dutch",
#	"nn":
	"no": "Norwegian",
#	"nv":
#	"ny":
	"oc": "Occitan",
#	"oj":
	"om": "(Afan) Oromo",
	"or": "Oriya",
	"pa": "Punjabi",
	"pl": "Polish",
	"ps": "Pashto, Pushto",
	"pt": "Portuguese",
	"qu": "Quechua",
	"rm": "Rhaeto-Romance",
	"rn": "Kirundi",
	"ro": "Romanian",
	"ru": "Russian",
	"rw": "Kinyarwanda",
	"sa": "Sanskrit",
	"sd": "Sindhi",
	"se": "Swedish",
	"sg": "Sangro",
	"sh": "Serbo-Croatian",
	"si": "Singhalese",
	"sk": "Slovak",
	"sl": "Slovenian",
	"sm": "Samoan",
	"sn": "Shona",
	"so": "Somali",
	"sq": "Albanian",
	"sr": "Serbian",
	"ss": "Siswati",
	"st": "Sesotho",
	"su": "Sundanese",
	"sv": "Swedish",
	"sw": "Swahili",
	"ta": "Tamil",
	"te": "Tegulu",
	"tg": "Tajik",
	"th": "Thai",
	"ti": "Tigrinya",
	"tk": "Turkmen",
	"tl": "Tagalog",
	"tn": "Setswana",
	"to": "Tonga",
	"tr": "Turkish",
	"ts": "Tsonga",
	"tt": "Tatar",
	"tw": "Twi",
	"ug": "Ugandan",
	"uk": "Ukrainian",
	"ur": "Urdu",
	"uz": "Uzbek",
	"vi": "Vietnamese",
	"vo": "Volapuk",
	"wo": "Wolof",
	"xh": "Xhosa",
#	"yi":
	"yo": "Yoruba",
	"zh": "Chinese",
	"cn": "Chinese",
	"zu": "Zulu",
	"bs": "Bosnian",
	"iu": "Inuktitut",
	"xx": "No Language",
}
