# -*- coding: utf-8 -*-

import base64
from .template import HTTPRequestHandlerTemplate
from time import time
import subprocess
import select
import os

# #################################################################################################

class PlayliveTVHTTPRequestHandler(HTTPRequestHandlerTemplate):
	'''
	Http request handler that implements playlive handler that extracts channel key generated by bouquet generator
	and redirects to real stream url
	'''
	def __init__(self, content_provider, addon, cache_life=900):
		super(PlayliveTVHTTPRequestHandler, self).__init__(content_provider, addon)
		self.live_cache = {}
		self.cache_life = cache_life

	# #################################################################################################

	def decode_channel_key(self, path):
		if path.endswith('.m3u8'):
			path = path[:-5]

		if path.endswith('.mpd'):
			path = path[:-4]

		return base64.b64decode(path.encode('utf-8')).decode("utf-8")

	# #################################################################################################

	def get_url_by_channel_key(self, channel_key):
		'''
		This is default implementation, that just forwards this call to content provider.
		Replace it with your own implementation if you need something different.
		'''
		return self.cp.get_url_by_channel_key(channel_key)

	# #################################################################################################

	def P_playlive(self, request, path):
		channel_key = self.decode_channel_key(path)

		if self.cache_life > 0 and channel_key in self.live_cache and self.live_cache[channel_key]['life'] > int(time()):
			result = self.live_cache[channel_key]['result']
		else:
			result = self.get_url_by_channel_key(channel_key)

			if not result:
				return self.reply_error404(request)

			if self.cache_life > 0:
				self.live_cache[channel_key] = {
					'life': int(time()) + self.cache_life,
					'result': result
				}

		return self.reply_redirect(request, result)

	# #################################################################################################

	def P_playlivets(self, request, path):
		return self.convert_stream_to_ts(request, self.cp.http_endpoint + '/playlive/' + path)

	# #################################################################################################

	def convert_stream_to_ts(self, request, input_url):
		cmd = [
			'/usr/bin/ffmpeg',
			'-nostdin',
			'-loglevel', 'info',
			'-i', input_url,
			'-map', '0:v:0',
			'-map', '0:a:0',
			'-c:v', 'copy',
			'-c:a', 'copy',
			'-muxdelay', '0',
			'-muxpreload', '0',
			'-mpegts_flags', '+resend_headers',
			'-f', 'mpegts',
			'pipe:1'
		]

		if os.path.isfile('/usr/lib/exteplayer3_deps/ffmpeg'):
			cmd[0] = '/usr/lib/exteplayer3_deps/ffmpeg'

		# cmd = [
		# 	'/usr/bin/gst-launch-1.0',
		# 	'urisourcebin', 'uri=' + input_url, 'name=src',
		# 	'mpegtsmux', 'name=mux', 'pat-interval=100000000', 'pmt-interval=100000000', '!', 'fdsink', 'fd=1',
		# 	'src.', '!', 'parsebin', 'name=vparse', '!', 'queue', '!', 'mux.',
		# 	'src.', '!', 'parsebin', 'name=aparse', '!', 'queue', '!', 'mux.'
		# ]

		process = None
		log = None

		try:
			self.cp.log_info("Starting stream conversion to TS for URL: %s" % input_url)

#			log = open('/tmp/archivczsk-ffmpeg.log-%s' % input_url.split('/')[-1], 'w')
			log = open(os.devnull, 'w')

			poll_obj = select.poll()
			process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=log, bufsize=0)
			poll_obj.register(process.stdout, select.POLLIN)
			poll_obj.register(request.wfile, select.POLLIN | select.POLLHUP | select.POLLERR)

			request.send_response(200)
			request.send_header('Content-Type', 'video/mp2t')
			request.send_header('Cache-Control','no-cache')
			request.send_header('Connection', 'close')

			while True:
				events = poll_obj.poll(1000)  # 6 second timeout
				if not events:
					continue

				for fd, event in events:
					if fd == request.wfile.fileno():
#						if event & (select.POLLHUP | select.POLLERR):
						raise IOError("Client disconnected")

				for fd, event in events:
					if fd == process.stdout.fileno():
						data = process.stdout.read(65536)

						if not data:
							break

						request.write(data)

		except (IOError, OSError):
			self.cp.log_debug("Stopping stream conversion for URL: %s - client disconnected" % input_url)

		except:
			self.cp.log_exception()

		finally:
			if process:
				try:
					if process.poll() is None:
#						process.terminate()
						process.kill()

						try:
							process.wait()
						except:
							self.cp.log_error("Failed to stop ffmpeg process for URL: %s" % input_url)
							self.cp.log_exception()

				except:
					self.cp.log_error("Failed to kill ffmpeg process for URL: %s" % input_url)
					self.cp.log_exception()

				try:
					poll_obj.unregister(process.stdout)
					poll_obj.unregister(request.wfile)
					process.stdout.close()
				except:
					self.cp.log_exception()

			if log:
				log.close()

			self.cp.log_info("Stream conversion for URL %s stopped" % input_url)

		return None

# #################################################################################################
